### ISSUE TITLE
[Bug] Received NaN for the `children` attribute

### ISSUE THREAD

**Issue by D3nn7** [DanielKraemer/fizzbuzz-react-ts#1]
If you use a button the error was thrown by react-dom. I think you use the wrong type.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79147263/168640530-597af8b6-4341-4360-b17f-b1395b5dacb9.png">

**Comment by D3nn7** [comment]
You can assign this to me.

**Comment by DanielKraemer** [comment]
@D3nn7 this is currently work in progress.
I hope I'll fix this today

**Comment by DanielKraemer** [comment]
Oh there was an issue for this :rofl: 
Fixed this today :sweat_smile:
